manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: urob
      url-base: https://github.com/urob
    # - name: aepfli
    #   url-base: https://github.com/aepfli
    - name: petejohanson
      url-base: https://github.com/petejohanson
    # - name: englmaxi
    #   url-base: https://github.com/englmaxi
    - name: badjeff
      url-base: https://github.com/badjeff
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: cirque-input-module
      remote: badjeff
      revision: main
    - name: zmk-input-behavior-listener
      remote: badjeff
      revision: main
  self:
    path: config
